<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemDefinitionGroup>
    <ClCompile>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <PrecompiledHeaderFile>PreCompile.h</PrecompiledHeaderFile>
    </ClCompile>
    <Link>
      <AdditionalDependencies>
      </AdditionalDependencies>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>

  <ItemGroup>
    <ClCompile Include="..\Wrapper\PreCompile.cpp">
      <PrecompiledHeader>Create</PrecompiledHeader>
    </ClCompile>
  </ItemGroup>

</Project>
