<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>ViewCs</RootNamespace>
    <TargetFrameworks>
      net48;
    </TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <ProjectReference Include="..\Cli.Net8\Wrapper.Net80.vcxproj" />
    <ProjectReference Include="..\WpfControl\WpfControl.NetOld.csproj" />
  </ItemGroup>

  <Import Project="Targets.props" />

</Project>
