<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86;Any CPU</Platforms>
    <RootNamespace>ViewCs</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <ProjectReference Include="..\Wrapper\Wrapper.Net80.vcxproj" />
    <ProjectReference Include="..\WpfControl\WpfControl.csproj" />
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)\Targets.props" />
  <Import Project="$(MSBuildThisFileDirectory)\Lang\ResGen.NetSdk.props" />

</Project>
