<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>8.0</LangVersion>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86;Any CPU</Platforms>
    <RootNamespace>ViewCs</RootNamespace>
    <TargetFrameworks>
      net45;
      net48;
    </TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cli.Net8\Wrapper.Net80.vcxproj" />
    <ProjectReference Include="..\WpfControl\WpfControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MainWindow.xaml.cs" />
    <Compile Include="MySampleModel.cs" />
  </ItemGroup>

</Project>
