<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <CONFIG_NAME>$(Platform)-$(Configuration)</CONFIG_NAME>
    <OUTDIR_CONFIG>$(CONFIG_NAME)\$(TargetFramework)</OUTDIR_CONFIG>
  </PropertyGroup>

  <!--  NET プロジェクト (C#, VB.NET) の設定  -->
  <PropertyGroup
      Condition="'$(MSBuildProjectExtension)' != '.vcxproj'">
    <IntDir>$(OBJ_BASE_DIR)\$(CONFIG_NAME)\$(MSBuildProjectName)\</IntDir>
    <IntermediateOutputPath>$(IntDir)</IntermediateOutputPath>
    <OutDir>$(LIB_BASE_DIR)\$(OUTDIR_CONFIG)\$(MSBuildProjectName)\</OutDir>
  </PropertyGroup>

  <!--  C++/CLI ラッパーの設定  -->
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj' And '$(TargetFramework)' != ''">
    <IntDir>$(OBJ_BASE_DIR)\$(OUTPUT_CONFIG)\$(MSBuildProjectName)\</IntDir>
    <OutDir>$(LIB_BASE_DIR)\$(OUTPUT_CONFIG)\$(MSBuildProjectName)\</OutDir>
  </PropertyGroup>

  <!--  C++ プロジェクトの設定  -->
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj' And '$(TargetFramework)' == ''">
    <IntDir>$(OBJ_BASE_DIR)\$(CONFIG_NAME)\Native\$(MSBuildProjectName)\</IntDir>
    <OutDir>$(LIB_BASE_DIR)\$(CONFIG_NAME)\Native\$(MSBuildProjectName)\</OutDir>
  </PropertyGroup>

</Project>
