<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemGroup>
    <ClInclude Include="PreCompile.h" />
    <ClInclude Include="resource.h" />
    <ClInclude Include="Wrapper.h" />
    <ClInclude Include="WrapperNamespace.h" />
  </ItemGroup>

  <ItemGroup>
    <ClCompile Include="AssemblyInfo.cpp" />
    <ClCompile Include="Wrapper.cpp" />
  </ItemGroup>

  <ItemGroup>
    <Text Include="ReadMe.txt" />
  </ItemGroup>
  <ItemGroup>
    <ResourceCompile Include="app.rc" />
  </ItemGroup>
  <ItemGroup>
    <Image Include="app.ico" />
  </ItemGroup>

</Project>
