<?xml version="1.0" encoding="utf-8"?>
<Project>

  <ItemGroup>
    <EmbeddedResource  Update="Lang\String.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>String.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource  Update="Lang\String.ja.resx" />
  </ItemGroup>

</Project>
